# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qa.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08qa.proto\x12\tqaservice\"#\n\x0fQuestionRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"\"\n\x10QuestionResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2U\n\tQAService\x12H\n\x0b\x41skQuestion\x12\x1a.qaservice.QuestionRequest\x1a\x1b.qaservice.QuestionResponse\"\x00\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qa_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _globals['_QUESTIONREQUEST']._serialized_start=23
  _globals['_QUESTIONREQUEST']._serialized_end=58
  _globals['_QUESTIONRESPONSE']._serialized_start=60
  _globals['_QUESTIONRESPONSE']._serialized_end=94
  _globals['_QASERVICE']._serialized_start=96
  _globals['_QASERVICE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
