# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import qa_pb2 as qa__pb2


class QAServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskQuestion = channel.unary_unary(
                '/qaservice.QAService/AskQuestion',
                request_serializer=qa__pb2.QuestionRequest.SerializeToString,
                response_deserializer=qa__pb2.QuestionResponse.FromString,
                )


class QAServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AskQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AskQuestion,
                    request_deserializer=qa__pb2.QuestionRequest.FromString,
                    response_serializer=qa__pb2.QuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qaservice.QAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QAService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AskQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qaservice.QAService/AskQuestion',
            qa__pb2.QuestionRequest.SerializeToString,
            qa__pb2.QuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
